### ISSUE TITLE
Slovak translation for Picon updater plugin

### ISSUE THREAD

**Issue by MichalMia** [s3n0/e2plugins#18]
Hello. I took the liberty of slightly modifying the Slovak translation of the plugin. I also took the liberty of editing 2 images that are displayed in enigma as the logo of the plugin.
I compiled these 3 modified files into a flood ipk installation. I did not make any other changes in the ipk installation package. To distinguish it from the previous version of IPK, I added the letter M to the end of the name of the one I modified.
I am attaching the picture files.

![plugin](https://github.com/s3n0/e2plugins/assets/165143726/f4b162fc-81c5-43d2-8af4-dfae2157eafe)
![plugin_fhd](https://github.com/s3n0/e2plugins/assets/165143726/438977e2-fe5a-438b-9e21-22ce80df4194)

[https://picon.cz/wp-content/uploads/asgarosforum/750/Extensions-Picons-Chocholousek_5.0.231225_all_M.7z](url)

Michal

**Comment by s3n0** [comment]
Hi.

I don't understand what it is about at all. Do you want me to change the LOGO of the plugin that people have been used to since its inception ? :-)

Sorry, but I don't like this LOGO anyway. At lower resolutions, the LOGO is barely visible and it will not be obvious at all in this small LOGO that there are some picons inside the small graphic. It will not clearly follow from the LOGO that it is the LOGO of the channels. I designed the LOGO quickly, but in such a way... that it was simple... and at the same time understandable that it is the LOGO of the channel :-/.

As for the translation... is there anything else that can be translated ? I think he can't. But when you create a pull request for SK language translation, I'll look into it. I am also Slovak, so... there will be no problem with translation :-). Only if in the improvement of some used terms. However, the problem also arises here that if users in Slovakia are used to one exact term, then it is not a good idea to change it to a completely different term :-/.
