### ISSUE TITLE
DVB-T2  Picons

### ISSUE THREAD

**Issue by C74K** [s3n0/e2plugins#8]
I am from Poland and i wanna know how to update Picons because part of channels on DVB-T2 are cloned from DVB-S2.

**Comment by s3n0** [comment]
Hi. 

Picons for DVB-T/T2 are not being developed for Poland yet. 

In general, there is a problem with bands for DVB-T/T2, because there are always many different providers of DVB-T/T2 services and many different transmitters with different transmission parameters (frequencies / transponders / multiplexes / ...). It is difficult to monitor and constantly update the icons for DVB-T/T2. Therefore, currently only DVB-T/T2 packages with picons are available only for the CZ + SK country. 

For more info, however, you must contact Chocholousek, who is a picon designer (I'm just a developer of the enigma2-plugin for his picons):

https://www.linuxsat-support.com/thread/124700-picons-by-chocholou%C5%A1ek/?pageNo=1
https://picon.cz/forum/forum/support/
https://github.com/chocholousek

**Comment by chocholousek** [comment]
> I am from Poland and i wanna know how to update Picons because part of channels on DVB-T2 are cloned from DVB-S2.

Yes s3n0 is right, but there are also Greek and Italian DTT picons. However, without help, I would not be able to produce these. Does someone have to provide me with a setting with the Polish DTT and regularly inform about all changes, otherwise it doesn't make sense.

**Comment by C74K** [comment]
ok.
whats you need ??

**Comment by s3n0** [comment]
I'll explain it in more detail ... :)

Chocholoušek needs **regular** news announcements from an Enigma user who regularly monitors this particular and lesser-known DVB provider. You must report new channel logos regularly if they change, as well as service reference codes if they change.

This means freshly tuned terrestrial TV channels - in the "userbouquet.*.tv" files and also the "lamedb" file, which is a database for assigning names to the serv.ref.codes in the userbouquet file. Ideally, the "settings" would be zipped. For example, using the E-Channelizer or DreamboxEdit tool, you download a list of channels from your set-top box and then zip and send it to Chocholoušek. However, you must do this **regularly**, with each change.

Chocholoušek opens this list in his PC and checks new logos or their service reference codes. However, it is quite a complicated job.

It would be best if you were directly announcing what had changed, which channel had changed - whether the design of the specific TV channel logo had changed, or whether the reference code of a TV channel had changed.

Chocholoušek is a picon designer. He monitors a large number of satellite positions and their channels (mainly satellite channels). He monitors their changes in changing picons as well as in changing service reference codes.

It's really a very demanding job - watching so many different DVB channels. Therefore, it is important that a person **regularly** reports all changes in time :). And this is not a 1 month commitment, but you have to do this for many years. Because if you decide, for example, not to send new information about a terrestrial provider in 2 years, then Chocholoušek will also stop updating the icons for your Polish DVB-T/T2 provider.

Local DVB-T/T2 providers are a particularly big problem, because information about them cannot be found anywhere on the internet. Therefore, Enigma users are needed, such as those who regularly send all changes to the program menu, ie: change the service reference code, change the design of a TV channel logo, change the name, discover a new or delete a non-existent TV channel.

Minor changes to your Polish DVB-T/T2 provider, you can also announce through the discussion forum, for example here:
https://picon.cz/forum/
https://www.linuxsat-support.com/thread/124700-picons-by-chocholou%C5%A1ek/?pageNo=1

**EDIT:**

You also mentioned before a clone of channels from satellite. Do you mean that the provider broadcasts both on satellite (DVB-S) and also on broadcast (DVB-T) ? If there is an identical copy of all the program offer at your Polish provider, if it matches, then create a conversion table from the service reference codes on DVB-S to the codes for DVB-T. And it's done :). Then we can create, for example, a simple shell-script to convert service reference codes (.PNG file names). You can then use this yourself in your set-top box or Chocholousek (to create a pikon package especially only for your Polish DVB-T provider).

**Comment by C74K** [comment]
send to you file from vu+ by forum ?

**Comment by chocholousek** [comment]
Yes, go to https://picon.cz/forum register and save the setting DVB-T / T2 Poland with vu + as an attachment to the forum post.
